# Generated by Django 5.0.5 on 2024-05-07 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout', models.IntegerField(default=-1)),
                ('command', models.TextField()),
                ('key', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('passed', 'passed'), ('failed', 'failed'), ('todo', 'todo'), ('candidate', 'candidate'), ('candidate2', 'candidate2')], default='candidate', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('directory', models.TextField()),
                ('status', models.CharField(choices=[('compiling', 'compiling'), ('pending', 'pending'), ('running', 'running'), ('failed', 'failed'), ('passed', 'passed')], default='compiling', max_length=9)),
                ('backup', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('url',), name='unique__url'),
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='modeling.project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modeling.group'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='modeling.project'),
        ),
        migrations.AddField(
            model_name='trial',
            name='testcase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='modeling.testcase'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='recent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='modeling.trial'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='unique__group__name__per_project'),
        ),
        migrations.AddConstraint(
            model_name='testcase',
            constraint=models.UniqueConstraint(fields=('project', 'key'), name='unique__testcase__key__per__project'),
        ),
    ]
