# Generated by Django 5.0.5 on 2024-05-08 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modeling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('failed', models.ManyToManyField(blank=True, related_name='failed_snapshots', to='modeling.testcase')),
                ('passed', models.ManyToManyField(blank=True, related_name='passed_snapshots', to='modeling.testcase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='modeling.project')),
                ('todo', models.ManyToManyField(blank=True, related_name='todo_snapshots', to='modeling.testcase')),
                ('unverified', models.ManyToManyField(blank=True, related_name='unverified_snapshots', to='modeling.testcase')),
            ],
        ),
    ]
